---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Standardized Precipitation Evapotranspiration Calculation

## Objectif

Ce document vise à calculer l'indice Standardized Precipitation Evapotranspiration Index (SPEI), une des variables de contrôle intégrées dans l'analyse. L'ajout de cette variable permet de réduire la variabilité inexpliquée du modèle et estimer plus précisément l'effet du traitement. Nous calculons l'indice à partir d'une référence à long terme de 1981 à 2021, en utilisant les données mensuelles de précipitation, de température minimale et maximale provenant de Worlclim. Le calcul du SPEI est effectué en plusieurs étapes en utilisant la méthode de Hargreaves ( Modified-Hargreaves methods) définie par Droogers et Allen @2002 pour estimer l'évapotranspiration potentielle (PET), puis en intégrant ce calcul dans un indice global de sécheresse.

## Méthode

Nous avons chargé le dataframe contenant les données sur la précipitation, la température minimale et la température maximale pour chaque clusters. A partir des coordonnées géométriques de chaque clusters, nous calculons la latitude, qui nous servira de base de calcul pour estimer l'évapotranspiration potentielle (PET). Le calcul de la latitude garantira que l'estimation du PET est spécifique aux conditions géographiques locales. Nous récupérons ensuite les séries temporelles mensuelles des variables climatiques de chaque cluster: température minimale (tmin), température maximale (tmax), précipitation (prec). A travers la formule de Hargreaves, nous estimons le PET et le bilan hybride (c'est-à-dire la différence entre la précipitation et le PET). Le bilan hybride est converti en série temporelle, à partir de laquelle l'indice SPEI est estimé sur une échelle de trois mois, en utilisant une période de référence de 1980 à 2021. Pour une analyse plus globale, on agrège les résultats à l'échelle annuelle en calculant la moyenne annuelle des valeurs de SPEI par année pour chaque cluster.

```{r}

library(SPEI)
library(tidyverse) #Manipulation et visualisation des données
library(sf) #Analyse des données spatiales
library(tmap) #Analyse cartographique
library(labelled) # Manipulation des labels
library(tibbletime)
library(zoo)
library(dplyr)
library(readr)
library(lubridate)

# Load data 
spatial_covars <- read_rds("data/derived/spatial_covars.rds")


# Latitude calculation
spatial_covars_spei <- spatial_covars %>% 
  mutate(
    lat = st_coordinates (st_centroid(geometry))[,2])
  
# Extract the first cluster's climate time series
row1 <- spatial_covars [1,]

# Extract vectors 
tmin <- row1$temperature_min_wc[[1]]$value
tmax <- row1$temperature_max_wc[[1]]$value
prec <- row1$precipitation_wc[[1]]$value
dates <- row1$temperature_min_wc[[1]]$datetime
lat <- row1$LATNUM


# Compute reference evapotranspiration (PET) using modified Hargreaves (Droogers & Allen)
pet <- hargreaves(Tmin = tmin, Tmax = tmax, Pre = prec, lat = lat)

# Compute water balance
wb <- prec - pet

# Turn to time series
wb_ts <- ts(wb, start = c(year(min(dates)), month(min(dates))), frequency = 12)

# Compute SPEI 
spei_obj <- spei(wb_ts, 
                 scale = 12,
                 ref.start = c(1980,1),
                 ref.end = c(2021,12))

# Turn into tibble
spei_tbl <- tibble(
  datetime = dates, 
  spei = as.numeric(spei_obj$fitted)
) %>%
  mutate(year = year(datetime)) %>%
  group_by(year) %>%
  summarise(
    spei_mean = mean(spei, na.rm = TRUE)
  )

# SPEI sous forme de map
spatial_covars_spei <- spatial_covars %>%
  mutate(
    spei_wc = pmap(
      list(tmin = temperature_min_wc,
           tmax = temperature_max_wc,
           prec = precipitation_wc,
           lat = lat),
      function(tmin, tmax, prec, lat) {
        data_tmin <- data.frame(date = tmin$datetime, tmin = tmin$value)
        data_tmax <- data.frame(date = tmax$datetime, tmax = tmax$value)
        data_prec <- data.frame(date = prec$datetime, prec = prec$value)
        
        # Merge
        data_merged <- reduce(list(data_tmin, data_tmax, data_prec), merge, by = "date")
        
        # Delete lines with NA
        data_clean <- na.omit(data_merged)
        
        # If cleaned data are insufficient, return NA 
        if (nrow(data_clean) < 12) {
          return(tibble(datetime = data_merged$date, spei = NA_real_))
        }
        
        # Extract clean columns
        tmin_synced <- data_clean$tmin
        tmax_synced <- data_clean$tmax
        prec_synced <- data_clean$prec
        dates_synced <- data_clean$date
        
        # PET Calculation
        pet <- hargreaves(
          Tmin = tmin_synced,
          Tmax = tmax_synced,
          Pre = prec_synced,
          lat = lat
        )
        
        wb <- prec_synced - pet
        
        wb_ts <- ts(wb, start = c(year(min(dates_synced)), month(min(dates_synced))), frequency = 12)
        
        spei_obj <- spei(wb_ts, 
                         scale = 12, 
                         ref.start = c(1980,1),
                         ref.end = c(2021,12))
        
        # Result
        tibble(datetime = dates_synced, spei = as.numeric(spei_obj$fitted)) %>%
          mutate(year = year(datetime)) %>%
          group_by(year) %>%
          summarise(
            spei_mean = mean(spei, na.rm = TRUE)
          )
        
      }
    )
  )

# Enregistrement
spatial_covars_spei <- as.data.frame(spatial_covars_spei)
write_rds(x = spatial_covars_spei, file = "data/derived/spatial_covars_spei.rds")
```
