---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Estimation

## Objectif

Le document présente l'estimation en double différence des groupes de traitement et de contrôle pour la période 1997- 2021. Le principe est de comparer l'indice de richesse des ménages de contrôle et de traitement à une période antérieure et une période postérieure à la mise en place des aires protégées.

## Methods

1.  Définition des périodes de traitement

    -   Période de pré-traitement: Aires protégées crées entre 1997 et 2008

    -   Période de post-traitement: Aires protégées crées entre 2008 et 2021 (71 AP créées sur 47 282 km²)

2.  Vérification de l'hypothèse des tendances parallèles

    -   Création d'un groupe de traitement placebo basé sur les ménages de 1997 (traitement= ménages situés à **≤** 10 km des aires protégées créées entre 2008 et 2021)

    -   Appariement du groupe de traitement placebo avec un groupe de contrôle placebo

    -   Représentation graphique de l'évolution des groupes en 1997, 2008 et 2021 pour une confirmation visuelle

    -   Effectuer un test placebo en faisant une estimation en double différence sur la période de pré-traitement (1997-2008): un effet non significatif confirmerait l'absence de tendances divergentes avant l'intervention

3.  Estimation du modèle DID

    -   Estimation du modèle DID en utilisant des erreurs standards robustes aux corrélations intra-grappes pour gérer la dépendance des observations au sein des grappes:

        -   calcul des résidus à partir du modèle de régression

        -   Utilisation des résidus calculés pour construire une matrice variance-covariance robuste, qui va ajuster la corrélation intra-grappe

## Definition of treatment periods

La période de pré-traitement sera les aires protégées créées entre 1997 et 2008. Le post-traitement sera les aires protégées créées entre 2008 et 2021.

```{r}

# Library 
library(tidyverse) #Manipulation et visualisation des données
library(tmap) #Analyse cartographique 
library(ggplot2) #Figure
library(sf)
library(gt) #Mise en forme des tableaux 
library(geodata) # Pour avoir le contour de Madagascar
library(units)

# Load data 
hr_1997_final <- readRDS("data/derived/hr_1997_final.rds")
hr_2008_final <- readRDS("data/derived/hr_2008_final.rds")
hr_2021_final <- readRDS("data/derived/hr_2021_final.rds")

# Systèmes de coordonnées de référence 
standard_crs <- 4326
mdg_crs <- 29702 

# Load boundary
contour_mada <- gadm(country = "Madagascar", level = 0, path = "data") %>%
  st_as_sf() %>%
  st_set_crs(standard_crs)

# PA data
sapm <- st_read("data/raw/sapm/SAPM_2017_corrected.shp") |> # en EPSG 9001
  st_transform(standard_crs) %>%
  st_make_valid() %>%
  mutate(YEAR_CREAT = year(ymd(DATE_CREAT)), .after = DATE_CREAT)

sapm_terrestre <- sapm %>% 
  st_intersection(contour_mada)%>%
  st_make_valid() %>%
  st_transform(mdg_crs) %>%
  mutate(`HECTARES_TERR` = as.numeric(st_area(.)) / 10000) %>%
  st_transform(standard_crs)

# Buffer de 10 km
buffer_dist <- 10000 

# Spécification des aires protégées avant 2008
sapm_before_2008 <- sapm_terrestre %>%
  filter(year(DATE_CREAT) < 2008)

# Spécification des aires protégées après 2008
sapm_from_2008 <- sapm_terrestre %>%
  filter(year(DATE_CREAT) >= 2008)

# Créer des buffers de 10 km autour des AP
buffer_10km_before_2008 <- sapm_before_2008 %>%
  st_transform(mdg_crs) %>%
  st_buffer(dist = buffer_dist) %>%
  st_make_valid() %>%
  st_union() %>%
  st_as_sf() %>%
  st_make_valid() %>%
  st_transform(standard_crs)

buffer_10km_from_2008 <- sapm_from_2008  %>%
  st_transform(mdg_crs) %>%
  st_buffer(dist = buffer_dist) %>% 
  st_make_valid() %>%
  st_union() %>%
  st_as_sf() %>%
  st_make_valid() %>%
  st_transform(standard_crs)
```
