---
title: "PA-livelihood-impact-dhs (Step)"
author: "Iriana Razafimahenina"
format: 
  html:
    code-summary: "voir le code" 
    embed-resources: true 
    code-fold: true
  execute: 
    warning: false
    error: false
editor: visual
editor-options: 
  chunk_output_type: console
bibliography: references.bib
---

# Environnement

Chargement des librairies nécessaires

```{r}
library(tidyverse) #Manipulation et visualisation des données
library(haven) #Importation des données 
library(writexl) #exportation de données
library(sf) #Analyse des données spatiales
library(tmap) #Analyse cartographique
library(codebook) #Documentation et mise en forme des données
library(gt) #Mise en forme des tableaux
library(survey) #Analyse des données d'enquêtes 
library(MatchIt) #Matching
library(ggplot2) #Figure 
```

# Data

Chargement des données sur:

-   Conditions socioéconomiques des ménages (DHS): DHS 1997, DHS 2008, DHS 2021

-   Environnement géophysique des ménages (mapme.biodiversity)

-   données sur les aires protégées: données de SGAP (SAPM)

# Calcul initial

Filtrer les ménages ruraux et les ménages proches des aires protégées créées à partir de 2008

## Buffer

-   Création d'un buffer de 10 km autour des aires protégées (dist = 1000)

## Treatment and Control groups assignment

-   [Groupe de traitement]{.underline}: ménage dans ou au moins à 10 km des aires protégées entre 2008 et 2021

-   [Groupe de contrôle]{.underline}: ménage à plus de 10 km des aires protégées entre 2008 et 2021

## Outcome variable

-   Variable de résultat principal: niveau de vie des ménages

    -   Récupération de la variable hv270a (wealth index de la zone rurale) pour l'année 2021

    -   Recalculer le wealth index hv270a pour 1997 et 2008

    -   Segmentation de wealth index en centiles

-   Variable de résultat secondaire: inégalité du niveau de vie

Calcul du Z score standardisé du wealth index

## Matching variable

Chargement des données et extraction des données:

-   Couvert forestier en 2000 (Hansen et al.2013)

-   Pente et altitude (NASA SRTM)

-   Densité de population en 2000 (Worldpop)

-   Accessibilité en 2000 (JRC, Uchida et Nelson 2011)

## Control variable

-   Ajout des variables âges et sexes dans l'analyse

-   Chargement des données sur les précipitations et calcul de l'indice SPEI

# Matching

## Genetic matching 

-   Réalisation du matching avec la fonction de GenMatch() du package R MatchIt

-   Application de Mahalanobis Distance Matching

-   Utilisation du caliper à un intervalle de 0.25 écart-type de la distance de Mahalanobis

## Analyse de l'équilibre des covariables :

-   Avant matching pour déterminer les déséquilibres initiaux à partir du test de Standardized Mean Difference (SMD)

    -   Si SMD proche de 0, il existe un bon équilibre entre les groupes pour la covariable

    -   Si SMD \> 0.1, le déséquilibre est significatif donc on augmentera l'intervalle des calipers afin d'obtenir un SMD **≤** 0.1)

-   Après matching: Test visuel sur la qualité du matching

    Comparaison à partir du Q-Q Plot pour chaque covariable (dans le cas où le QQ plot se situe en diagonale, le quantile des 2 distributions sont similaires) \`\`\`

# Difference-in-difference

## Périodes de traitement

Définition des périodes de traitement:

-   Période de pré-traitement: Aires protégées crées entre 1997 et 2008

-   Période de post-traitement: Aires protégées crées entre 2008 et 2021 (71 AP crées sur 47 282 km²)

## Tendances parallèles

Vérification de l'hypothèse des tendances parallèles:

-   Création d'un groupe de traitement placebo basé sur les ménages de 1997 (traitement= ménages situés à **≤** 10 km des aires protégées créées entre 2008 et 2021)

-   Apparier le groupe de traitement placebo avec un groupe de contrôle placebo

-   Représentation graphique de l'évolution des groupes en 1997, 2008 et 2021 pour une confirmation visuelle

-   Effectuer un test placebo en faisant une estimation en double différence sur la période de pré-traitement (1997-2008): un effet non significatif confirmerait l'absence de tendances divergentes avant l'intervention

## Estimation du modèle DID

Estimation du modèle DID en utilisant des erreurs standards robustes aux corrélations intra-grappes pour gérer la dépendance des observations au sein des grappes:

-   calcul des résidus à partir du modèle de régression

-   Utilisation des résidus calculés pour construire une matrice variance-covariance robuste, qui va ajuster la corrélation intra-grappe

# Tests de Robustesse

## Variation des tailles de buffer

### Test pour une distance de 5 km 

#### Treatment and Control groups assignment

-   [Groupe de traitement]{.underline}: ménage dans ou au moins à 5 km des aires protégées entre 2008 et 2021

-   [Groupe de contrôle]{.underline}: ménage à plus de 5 km des aires protégées entre 2008 et 2021

#### Outcome variable

-   Variable de résultat principal: niveau de vie des ménages

    -   Récupération de la variable hv270a (wealth index de la zone rurale) pour l'année 2021

    -   Recalculer le wealth index hv270a pour 1997 et 2008

    -   Segmentation de wealth index en centiles

-   Variable de résultat secondaire: inégalité du niveau de vie

Calcul du Z score standardisé du wealth index

#### Matching variable

Chargement des données et extraction des données:

-   Couvert forestier en 2000 (Hansen et al.2013)

-   Pente et altitude (NASA SRTM)

-   Densité de population en 2000 (Worldpop)

-   Accessibilité en 2000 (JRC, Uchida et Nelson 2011)

#### Control variable

-   Ajout des variables âges et sexes dans l'analyse

-   Chargement des données sur les précipitations et calcul de l'indice SPEI

#### Matching

##### Genetic matching 

-   Réalisation du matching avec la fonction de GenMatch() du package R MatchIt

-   Application de Mahalanobis Distance Matching

-   Utilisation du caliper à un intervalle de 0.25 écart-type de la distance de Mahalanobis

##### Analyse de l'équilibre des covariables :

-   Avant matching pour déterminer les déséquilibres initiaux à partir du test de Standardized Mean Difference (SMD)

    -   Si SMD proche de 0, il existe un bon équilibre entre les groupes pour la covariable

    -   Si SMD \> 0.1, le déséquilibre est significatif donc on augmentera l'intervalle des calipers afin d'obtenir un SMD **≤** 0.1)

-   Après matching: Test visuel sur la qualité du matching

    Comparaison à partir du Q-Q Plot pour chaque covariable (dans le cas où le QQ plot se situe en diagonale, le quantile des 2 distributions sont similaires) \`\`\`

#### Difference-in-difference

##### Périodes de traitement

Définition des périodes de traitement:

-   Période de pré-traitement: Aires protégées crées entre 1997 et 2008

-   Période de post-traitement: Aires protégées crées entre 2008 et 2021 (71 AP crées sur 47 282 km²)

##### Tendances parallèles

Vérification de l'hypothèse des tendances parallèles:

-   Création d'un groupe de traitement placebo basé sur les ménages de 1997 (traitement= ménages situés à **≤** 5 km des aires protégées créées entre 2008 et 2021)

-   Apparier le groupe de traitement placebo avec un groupe de contrôle placebo

-   Représentation graphique de l'évolution des groupes en 1997, 2008 et 2021 pour une confirmation visuelle

-   Effectuer un test placebo en faisant une estimation en double différence sur la période de pré-traitement (1997-2008): un effet non significatif confirmerait l'absence de tendances divergentes avant l'intervention

##### Estimation du modèle DID

Estimation du modèle DID en utilisant des erreurs standards robustes aux corrélations intra-grappes pour gérer la dépendance des observations au sein des grappes:

-   calcul des résidus à partir du modèle de régression

-   Utilisation des résidus calculés pour construire une matrice variance-covariance robuste, qui va ajuster la corrélation intra-grappe

### Test pour une distance de 15km

#### Treatment and Control groups assignment

-   [Groupe de traitement]{.underline}: ménage dans ou au moins à 15 km des aires protégées entre 2008 et 2021

-   [Groupe de contrôle]{.underline}: ménage à plus de 15 km des aires protégées entre 2008 et 2021

#### Outcome variable

-   Variable de résultat principal: niveau de vie des ménages

    -   Récupération de la variable hv270a (wealth index de la zone rurale) pour l'année 2021

    -   Recalculer le wealth index hv270a pour 1997 et 2008

    -   Segmentation de wealth index en centiles

-   Variable de résultat secondaire: inégalité du niveau de vie

Calcul du Z score standardisé du wealth index

#### Matching variable

Chargement des données et extraction des données:

-   Couvert forestier en 2000 (Hansen et al.2013)

-   Pente et altitude (NASA SRTM)

-   Densité de population en 2000 (Worldpop)

-   Accessibilité en 2000 (JRC, Uchida et Nelson 2011)

#### Control variable

-   Ajout des variables âges et sexes dans l'analyse

-   Chargement des données sur les précipitations et calcul de l'indice SPEI

#### Matching

##### Genetic matching 

-   Réalisation du matching avec la fonction de GenMatch() du package R MatchIt

-   Application de Mahalanobis Distance Matching

-   Utilisation du caliper à un intervalle de 0.25 écart-type de la distance de Mahalanobis

##### Analyse de l'équilibre des covariables :

-   Avant matching pour déterminer les déséquilibres initiaux à partir du test de Standardized Mean Difference (SMD)

    -   Si SMD proche de 0, il existe un bon équilibre entre les groupes pour la covariable

    -   Si SMD \> 0.1, le déséquilibre est significatif donc on augmentera l'intervalle des calipers afin d'obtenir un SMD **≤** 0.1)

-   Après matching: Test visuel sur la qualité du matching

    Comparaison à partir du Q-Q Plot pour chaque covariable (dans le cas où le QQ plot se situe en diagonale, le quantile des 2 distributions sont similaires) \`\`\`

#### Difference-in-difference

##### Périodes de traitement

Définition des périodes de traitement:

-   Période de pré-traitement: Aires protégées crées entre 1997 et 2008

-   Période de post-traitement: Aires protégées crées entre 2008 et 2021 (71 AP crées sur 47 282 km²)

##### Tendances parallèles

Vérification de l'hypothèse des tendances parallèles:

-   Création d'un groupe de traitement placebo basé sur les ménages de 1997 (traitement= ménages situés à **≤** 15 km des aires protégées créées entre 2008 et 2021)

-   Apparier le groupe de traitement placebo avec un groupe de contrôle placebo

-   Représentation graphique de l'évolution des groupes en 1997, 2008 et 2021 pour une confirmation visuelle

-   Effectuer un test placebo en faisant une estimation en double différence sur la période de pré-traitement (1997-2008): un effet non significatif confirmerait l'absence de tendances divergentes avant l'intervention

##### Estimation du modèle DRDID

Estimation du modèle DID en utilisant des erreurs standards robustes aux corrélations intra-grappes pour gérer la dépendance des observations au sein des grappes:

-   calcul des résidus à partir du modèle de régression

-   Utilisation des résidus calculés pour construire une matrice variance-covariance robuste, qui va ajuster la corrélation intra-grappe

## FDR

Test des 3 hypothèses à partir de la méthode "False Directory Rate" de Benjamini-Hochberg pour contrôler le risque découvertes dans les hypothèses secondaires

## Sensibilité de Rosenbaum

Vérifier la robustesse des résultats issus du matching face à un éventuel biais non observé en testant différentes valeurs de Γ, afin d'évaluer dans quelle mesure la présence d'un biais caché pourraient influencer les conclusions de l'analyse

## Effets hétérogènes 

Estimation des effets hétérogènes en introduisant des interactions entre le traitement et les différentes variables différenciatrices dans un modèle de double DID pour explorer les effets différenciés des aires protégées sur les ménages en fonction des caractéristiques socio-démographiques et environnementales

Caractéristiques socio-démographiques et environnementales:

-   Sexe et âge du chef de ménage

-   Conditions environnementales (Pluviométrie, sécheresse)

-   Type de gouvernance des aires protégées (strictes (statuts IUCN I-IV) vs multi-usages ( statuts IUCN V-VI))

-   Distance aux aires protégées (5km, 10 km, 15 km)

-   Inégalité intra-communautaire (Z-score standardisée du wealth index)

## Pseudo Panel

-   Construction de cohorte de ménage

-   Estimation d'un modèle à effet fixe pour corriger les biais liées aux variables non observés

-   Pondérer les observations en fonction de la taille des cohortes

# Appendix

## Statistical power

-   EStimation de la probabilité de l'tudes à détecter un effet réel (le seuil de puissance attendu est communément fixée à 0.8 avec un seuil de signification fixée à 0.05)

-   Estimation de la puissance statistique pour détecter un effet d'au moins 7.5 centiles dans l'indice de richesse entre les groupes

-   Mobilisation des données MIS 2011, MIS 2013 et MIS 2016 si la puissance statistique est insuffisante
