---
title: "Supplementary material"
format: 
  docx:
    message: false
    warning: false
    error: false
    echo: false
    number-sections: true
    fig-width: 7
    fig-height: 5
  pdf:
    message: false
    warning: false
    error: false
    echo: false
    number-sections: true
  html:
    message: false
    warning: false
    error: false
    code-fold: true
    output-file: index.html
    number-sections: true
    toc: true
editor: visual
abstract: |
  This document uses a reproductible workflows to provide descriptive statistics accompanying the scientific article as title is 'Socioeconomic Impacts of Terrestrial Protected Areas: Evidence from Large-Scale National Surveys in Madagascar'. In section 1, we present the data sources and identification strategy and econometric methods used in the analysis. In section 2, we analyse the database on protected areas management evaluations to assess the absolute and relative importance of evaluation methods by type of countries.
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

# Pre-specified methods

## Data

### Protected areas {#protectedareas}

In our pre-analysis plan, we noticed that the data from the World Database on Protected Areas from [the protected planet portal](https://www.protectedplanet.net/en) was inaccurate for certain areas. The inaccuraties includes the classifications of IUCN status, incorrect creation dates, delineations that include buffer zones extending beyond the boundaries of PA. We therefore used the legal analysis carried out using CNLEGIS to identify early protections that are not registered in WDPA. Work to identify these cases was carried out by Bédécarrats and Seheno (Septembre 2024): <https://betsaka.github.io/conservation-dynamic-madagascar/>.

This study evaluates the impact of terrestrial PA creation on rural household well-being between 2008 and 2021. These time frame was chosen on the basis of the availability of geolocalised data on household living conditions and coincides with a period of strong expansion of PAs in the country, as shown in

## Empirical strategy

## Methods

# Departures and complements to the preanalysis plan

## Inclusion of MICS 2018

## Years-to-treatment binning

## Staggered DID estimator

## PA governance classification

We keep only terrestrial protected areas and discard marine or coastal protected areas. There is no consensus on IUCN categories in the literature. Ellason et al. [-@elleason2021] suggest the following classification, which we complement here with the naming used by the authors:

-   Some studies group I and II in one class, and all others in another class:

    -   Sharlemann et al. [-@scharlemann2010] classify cat. I and II as "protected sites with more restrictive land management regimes" and III to VI as "all other protected sites"

    -   Jones et al. [-@jones2018] designate I and II as "strict biodiversity conservation areas" and III to VI as "zones permitting certain human activities and sustainable resource extraction"

    -   Anderson and Mammides [-@anderson2020] designate only I and II as "areas in stricter categories".

-   Other studies group I, II and III in one class, and IV, V and VI in another class:

    -   Seiferling et al. [-@seiferling2012] designate I to III as "areas into high-protection" and IV to VI as "low protection categories".

    -   Françoso et al. [-@françoso2015] refer to IV to VI as "sustainable use PAs" and the other as "other".

-   Other studies group I to IV in one class and V and VI in another class:

    -   Nelson and Chomitz [-@nelson2011] refer to I to IV as "strict protection" and V and VI as "nonstrict or multi-use protection".

    -   Porter-Bordland et al. [-@porter-bolland2012] refer as I to IV as "protected areas" and V and VI as "community managed forests".

Adding to this classification, we share Ledberger [-@leberger2020] analysis that classifies the naturalness of IUCN category definition as follows: Ia = Ib \> II = III \> IV = VI \> V and they find out that "the global ranking of the effect of the IUCN categories on the forest loss per PA at the global scale, from the least to the most forest loss, was III \< Ia = Ib = II \< IV = V = VI" .

We consider that Lebergers et al. results [-@leberger2020] convincingly make the case to group I to III. We find out however that vivid debates focused on the category IV definition and revision [@leroux2010], so keep IV separated in our analysis, its purpose and criteria are different from V and VI[^suppl_material-1].

[^suppl_material-1]: From the literature, we could even consider also separating III in a separate category, to have 3 classes: I-II, III, IV and V-VI.

```{r}
# Drop marine, compute decade
wdpa2 <- wdpa_gee %>%
  filter(MARINE == "0") %>% #0: 100% terrestrial, 1: both, 2: 100% marine
  mutate(decade = STATUS_YR - (STATUS_YR %% 10),
         decade = case_when(
           decade == 0 ~ "Unknown",
           decade >0 & decade <= 1950 ~ "Before 1960",
           .default = paste(decade, decade+9, sep = "-")),
         type = ifelse(IUCN_CAT %in% c("Ia", "Ib", "II", "III"), "Strict",
                       ifelse(IUCN_CAT == "IV", "IV",
                              ifelse(IUCN_CAT %in% c("V", "VI"), "Nonstrict", 
                              "Unknown"))))
# Organize the order of display of decades, starting with Unnkown, then Before
decades <- wdpa2 %>%
  pluck("decade") %>%
  unique() %>%
  sort()
order_decades <- c("Before 1960", str_subset(decades, "^[0-9]")) 
wdpa2 <- wdpa2 %>%
  filter(decade != "Unknown") %>% 
  mutate(decade = factor(decade, levels = order_decades))
```

After this filtering, we have `r nrow(wdpa2)` protected areas for the analysis.
